### PR TITLE
Ensure BSD systems are built against OS execinfo lib

### PR DESCRIPTION
**Pull request by ring-pete**
*https://github.com/awslabs/aws-c-auth/issues/151*

On BSD systems we need to ensure we use the OS provided execinfo library.  Without passing this flag when the resulting cpython binary built by the awscrt will error out complaining about a missing backtrace symbol.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

> Thanks for taking a look at this!
> 
> Taking a peek at `CMakeLists.txt` here: https://github.com/awslabs/aws-c-common/blob/main/CMakeLists.txt it seems like i should be including the BSD execinfo library (although I am not a cmake expert by any means):
> 
> ```
> 95    elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
> 96        list(APPEND PLATFORM_LIBS dl m thr execinfo)
> ```
> 
> I can run some tests on my end today and see if I can figure out why this isn't being picked up by aws-c-auth.

Can you also see what happens if you just drop PLATFORM_LIBS entirely from the file?

### CODE REVIEW

**Review by bretambrose — COMMENTED** [review]
My initial reaction is that we shouldn't be setting PLATFORM_LIBS at all in here and that was likely a copy-and-paste error introduced years ago.

PLATFORM_LIBS should be inherited from aws-c-common.

**Comment by ring-pete** [comment]
Thanks for taking a look at this!

Taking a peek at `CMakeLists.txt` here: https://github.com/awslabs/aws-c-common/blob/main/CMakeLists.txt it seems like i should be including the BSD execinfo library (although I am not a cmake expert by any means):

```
95    elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
96        list(APPEND PLATFORM_LIBS dl m thr execinfo)
```

I can run some tests on my end today and see if I can figure out why this isn't being picked up by aws-c-auth.

**Comment by ring-pete** [comment]
Hello, hoping someone can revisit the PR to help get BSD support working.

**Comment by graebm** [comment]
BSD support was fixed a few months back by @knightjoel (Thanks again!)

Sorry for letting this old PR sit neglected, we have lot of repos to maintain and haven't always been the best at keeping on top of external contributions.

The fixes were in other repos. Here's some of that work:
https://github.com/awslabs/aws-c-common/pull/976
https://github.com/awslabs/aws-c-common/pull/979
https://github.com/awslabs/aws-c-common/pull/991
https://github.com/awslabs/aws-c-cal/pull/133
https://github.com/awslabs/aws-c-cal/pull/134
https://github.com/awslabs/aws-c-io/pull/553
https://github.com/awslabs/aws-c-io/pull/545

**Comment by ring-pete** [comment]
Thanks so much for the follow-up!  It's really appreciated and understandable how things can get lost in the shuffle.

**Pull request closed without merging**
